
services:
  backend:
    build: ./backend 
    container_name: blm_django_backend
    volumes:
      - ./backend:/backend 
      - staticfiles:/backend/staticfiles
      #- ./backend/db.sqlite3:/backend/db.sqlite3
      #- ./backend/staticfiles:/backend/staticfiles
      #- ./backend/media:/backend/media
    env_file:
      - ./backend/.env 
    ports:
      - "8000:8000"
    command: > 
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  frontend:
    build: ./frontend 
    container_name: blm_nextjs_frontend
    volumes:
      - ./frontend:/frontend 
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    command: npm run start 

  nginx:
    image: nginx:alpine
    container_name: blm_nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
      - staticfiles:/backend/staticfiles
      #- ./backend/staticfiles:/backend/staticfiles
      #- ./backend/media:/backend/media:ro
    depends_on:
      - frontend 
      - backend 

volumes:
  staticfiles:
